const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Behaviors.scrollto,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.MoveTo.Cnds.OnHitSolid,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Spritefont2.Acts.SetY
	];
};
self.C3_JsPropNameTable = [
	{Variables: 0},
	{Sprite: 0},
	{moving: 0},
	{checked: 0},
	{selected: 0},
	{moveleft: 0},
	{moveright: 0},
	{moveside: 0},
	{MoveTo: 0},
	{Solid: 0},
	{player: 0},
	{grid: 0},
	{TiledBackground: 0},
	{player_yellow: 0},
	{Sine: 0},
	{face: 0},
	{Touch: 0},
	{Browser: 0},
	{create: 0},
	{destroying: 0},
	{defeat: 0},
	{ScrollTo: 0},
	{gamemanager: 0},
	{player_red: 0},
	{player_blue: 0},
	{player_pink: 0},
	{player_purple: 0},
	{player_green: 0},
	{name: 0},
	{txtUI: 0},
	{Tween: 0},
	{btnSound: 0},
	{Rotate: 0},
	{Sine2: 0},
	{Bullet: 0},
	{confeti: 0},
	{confeti_explosion: 0},
	{txtUI2: 0},
	{Fade: 0},
	{flash: 0},
	{flash2: 0},
	{txtUI3: 0},
	{transition: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{sacar: 0},
	{nTuto: 0},
	{hand: 0},
	{arrow: 0},
	{best: 0},
	{Players: 0},
	{PlayerSPR: 0},
	{posX: 0},
	{posY: 0},
	{timetowait: 0},
	{SCORE: 0},
	{nColor: 0},
	{playerPosX: 0},
	{playersX: 0},
	{hit: 0},
	{scoreX: 0},
	{scoreY: 0},
	{cant: 0},
	{dragAngle: 0},
	{moveAngle: 0},
	{mag: 0},
	{dur: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newlayer: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0},
	{pX: 0},
	{pY: 0},
	{anim: 0},
	{txtX: 0},
	{txtY: 0}
];

self.InstanceType = {
	Variables: class extends self.IArrayInstance {},
	Sprite: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	grid: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	player_yellow: class extends self.I9PatchInstance {},
	face: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	gamemanager: class extends self.ISpriteInstance {},
	player_red: class extends self.I9PatchInstance {},
	player_blue: class extends self.I9PatchInstance {},
	player_pink: class extends self.I9PatchInstance {},
	player_purple: class extends self.I9PatchInstance {},
	player_green: class extends self.I9PatchInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	btnSound: class extends self.ISpriteInstance {},
	confeti: class extends self.ISpriteInstance {},
	confeti_explosion: class extends self.IParticlesInstance {},
	txtUI2: class extends self.ISpriteFontInstance {},
	flash: class extends self.ISpriteInstance {},
	flash2: class extends self.ISpriteInstance {},
	txtUI3: class extends self.ISpriteFontInstance {},
	transition: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	hand: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	best: class extends self.ISpriteInstance {},
	Players: class extends self.ISpriteInstance {},
	PlayerSPR: class extends self.I9PatchInstance {}
}